all:
	cd tinyxml; make
	cd libjson; make
	cd minilibs; make
	cd BBDevices; make
	cd Manager; make
	cd PwrControl; make
	cd WSServer; make
	cd MiniWWW; make
	cd logger; make
	cd utils; make

clean:

	cd tinyxml; make clean
	cd libjson; make clean
	cd minilibs; make clean
	cd BBDevices; make clean
	cd Manager; make clean
	cd PwrControl; make clean
	cd WSServer; make clean
	cd MiniWWW; make clean
	cd logger; make clean
	cd utils; make clean

install:

	cd tinyxml; make
	cd libjson; make
	cd minilibs; make
	cd BBDevices; make install
	cd Manager; make install
	cd PwrControl; make install
	cd WSServer; make install
	cd MiniWWW; make install
	cd logger; make install
	cd utils; make install
